### PR TITLE
Rebuild for r-base 4.4 and UCRT mingw toolchain

### PR DESCRIPTION
**Pull request by danielnachun**

### CODE REVIEW

**Comment by mfansler** [comment]
This will need https://github.com/conda-forge/r-maotai-feedstock/pull/7

**Comment by danielnachun** [comment]
Thanks, I was really stumped by this one!  I'll rerun the CI for this now.

**Comment by mfansler** [comment]
Yeah, this is a tricky one: if a recipe only adds `llvm-openmp  # [osx]` to `build:`, then the final metadata for run time requirements will set to use both the current pinned minimum (`llvm-openmp >=17.0.6`) and the one that was actually used in the `host:` environment (`llvm-openmp >=19.1.2`). That latter one then makes the build incompatible with other packages that have stricter requirements (like `r-base`). Kinda nasty.

Solution is just to always have the `llvm-openmp  # [osx]` in both `build:` and `host:`.

**Comment by danielnachun** [comment]
Thanks for the explanation, this was tricky!  This is now ready to merge.

**Pull request merged**
